name: estate-kit
services:
  odoo:
    image: docker.io/sumarokovvp/simplelogic:estate_kit_arm
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons:ro
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
    environment:
      - HOST=${DB_HOST:-host.containers.internal}
      - PORT=${DB_PORT:-5432}
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASSWORD:-odoo}
    depends_on: []

volumes:
  odoo-data:
